### ISSUE TITLE
Path to libclang in OSX

### ISSUE THREAD

**Issue by ssbanerje** [xavierd/clang_complete#362]
Hi,
I am having a problem with clang_complete running on my Mac OS Mavericks. When opening a file, I get an error saying --

```
Loading libclang failed, completion won't be available
Consider setting g:clang_library_path 
```

However, libclang is in the place it is supposed to be - `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib`

Does clang_complete search for it elsewhere? This seems to be a problem on Mavericks. It clang_complete under the same settings works perfectly on another box running Mountain Lion as well as a Linux box.

So I am not sure if this is a bug or is it a problem on that system? Could one of the devs clarify?

**Comment by seekerFactory** [comment]
Was facing the same(new at this :) ) and got a reference from http://tiku.io/questions/1747033/adding-clang-complete-to-homebrew-installed-vim-on-mac
Hence added this to ~/.vimrc:

let s:clang_library_path='/Library/Developer/CommandLineTools/usr/lib'
if isdirectory(s:clang_library_path)
    let g:clang_library_path=s:clang_library_path
endif
