### ISSUE TITLE
Confused by installation instructions

### ISSUE THREAD

**Issue by mvanaltvorst** [xavierd/clang_complete#568]
> Just put the files in `~/.vim/`

Which files is the README.md talking about? Should I just `git clone` the whole repo into `~/.vim/`? I feel like the README should be more clear about this.

**Comment by talih0** [comment]
I would suggest to use https://github.com/VundleVim/Vundle.vim as your vim plugin manager. 
Modify your .vimrc as per instructions on Vundle. 

Then, add:  Plugin 'rip-rip/clang_complete' in your .vimrc to install clang_complete.

**Comment by xaizek** [comment]
813aa270bd390bf64f03dc34f98834fb726a707d should help with this.
