### ISSUE TITLE
Clarification needed on statement "Just put the files in ~/.vim/"

### ISSUE THREAD

**Issue by SiteshSahoo** [xavierd/clang_complete#575]
Want to know in the below statement what **files** exactly refers to. 
Thanks!

**Comment by bdebyl** [comment]
Clone the repo under the directory, or use a vim plugin manager and reference the path accordingly.

**Comment by SanJacobs** [comment]
@bdebyl So, everything should go into `~/.vim/clang_complete/`? What does "reference the path accordingly" mean?

**Comment by bdebyl** [comment]
@SanJacobs with Vim Plugged (plugin manager) set-up and installed, adding this to your vimrc (or existing plugin inclusions):

```
" Plugged
call plug#begin('~/.vim/plugged')
Plug 'xavierd/clang_complete'
call plug#end()
```

Then, in vim, `:PlugInstall`. The README has a snippet right under the "Just put the files in ~/.vim/` illustrating the two commands needed to do so. 

If installing it manually, which I have no experience with, it should just work once the README commands are run and vim is reloaded/restarted. However, this snippet in your `~/.vimrc` should work if you have issues with it not "just working" -- after the README steps for manual installation is followed:

```
set runtimepath^=~/.vim/plugin/clang_complete.vim
```

Then reload/restart vim or run `:source ~/.vimrc`
